In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
A = np.random.rand(3,4)

In [3]:
A

array([[0.92092888, 0.40218799, 0.18123735, 0.19288555],
       [0.78815477, 0.70799252, 0.87968504, 0.01257624],
       [0.79319352, 0.81420399, 0.64577955, 0.9737995 ]])

In [4]:
ATA = A.T.dot(A)
AAT = A.dot(A.T)

In [5]:
ATA

array([[2.0984539 , 1.57421553, 1.37246282, 0.95995735],
       [1.57421553, 1.32593671, 1.22149819, 0.87935157],
       [1.37246282, 1.22149819, 1.22372398, 0.67488099],
       [0.95995735, 0.87935157, 0.67488099, 0.98564847]])

In [6]:
AAT

array([[1.079917  , 1.17243814, 1.36280911],
       [1.17243814, 1.89644527, 1.78193892],
       [1.36280911, 1.78193892, 2.65740078]])

In [7]:
ATA.T

array([[2.0984539 , 1.57421553, 1.37246282, 0.95995735],
       [1.57421553, 1.32593671, 1.22149819, 0.87935157],
       [1.37246282, 1.22149819, 1.22372398, 0.67488099],
       [0.95995735, 0.87935157, 0.67488099, 0.98564847]])

In [8]:
ATA

array([[2.0984539 , 1.57421553, 1.37246282, 0.95995735],
       [1.57421553, 1.32593671, 1.22149819, 0.87935157],
       [1.37246282, 1.22149819, 1.22372398, 0.67488099],
       [0.95995735, 0.87935157, 0.67488099, 0.98564847]])

In [9]:
d1,V = LA.eig(ATA)

In [10]:
d1

array([ 4.93643222e+00,  4.65580834e-01,  2.31749995e-01, -1.16487120e-16])

In [11]:
d1[-1]

-1.164871196659105e-16

In [12]:
V

array([[-0.62914356, -0.26803284,  0.69225722, -0.23047066],
       [-0.51644369, -0.01767343, -0.19897566,  0.83269577],
       [-0.46562647, -0.3008666 , -0.69307322, -0.46078281],
       [-0.34735614,  0.91505483, -0.02895072, -0.20292912]])

In [14]:
ATA.dot(V[:,1])

array([-0.12479095, -0.00822841, -0.14007772,  0.42603199])

In [15]:
d1[1]*V[:,1]

array([-0.12479095, -0.00822841, -0.14007772,  0.42603199])

In [16]:
idx = np.argsort(d1)[::-1]
d1 = d1[idx]
V = V[:,idx]

In [17]:
d1

array([ 4.93643222e+00,  4.65580834e-01,  2.31749995e-01, -1.16487120e-16])

In [18]:
V

array([[-0.62914356, -0.26803284,  0.69225722, -0.23047066],
       [-0.51644369, -0.01767343, -0.19897566,  0.83269577],
       [-0.46562647, -0.3008666 , -0.69307322, -0.46078281],
       [-0.34735614,  0.91505483, -0.02895072, -0.20292912]])

In [102]:
d2,U = LA.eig(AAT)
idx = np.argsort(d2)[::-1]
d2 = d2[idx]
U = U[:,idx]

In [103]:
d1

array([ 4.93643222e+00,  4.65580834e-01,  2.31749995e-01, -1.16487120e-16])

In [104]:
d2

array([4.93643222, 0.46558083, 0.23175   ])

In [105]:
U

array([[ 0.42240044, -0.19341623,  0.88553263],
       [ 0.57407015, -0.69895876, -0.4264975 ],
       [ 0.70144232,  0.68851058, -0.184206  ]])

In [106]:
d2

array([4.93643222, 0.46558083, 0.23175   ])

In [107]:
V

array([[-0.62914356, -0.26803284,  0.69225722, -0.23047066],
       [-0.51644369, -0.01767343, -0.19897566,  0.83269577],
       [-0.46562647, -0.3008666 , -0.69307322, -0.46078281],
       [-0.34735614,  0.91505483, -0.02895072, -0.20292912]])

In [108]:
U2,S2,V2 = LA.svd(A)

In [109]:
U

array([[ 0.42240044, -0.19341623,  0.88553263],
       [ 0.57407015, -0.69895876, -0.4264975 ],
       [ 0.70144232,  0.68851058, -0.184206  ]])

In [110]:
U2

array([[-0.42240044,  0.19341623,  0.88553263],
       [-0.57407015,  0.69895876, -0.4264975 ],
       [-0.70144232, -0.68851058, -0.184206  ]])

In [111]:
S2

array([2.22180832, 0.68233484, 0.48140419])

In [112]:
d2

array([4.93643222, 0.46558083, 0.23175   ])

In [113]:
d2**0.5

array([2.22180832, 0.68233484, 0.48140419])

In [114]:
V.T

array([[-0.62914356, -0.51644369, -0.46562647, -0.34735614],
       [-0.26803284, -0.01767343, -0.3008666 ,  0.91505483],
       [ 0.69225722, -0.19897566, -0.69307322, -0.02895072],
       [-0.23047066,  0.83269577, -0.46078281, -0.20292912]])

In [115]:
V2

array([[-0.62914356, -0.51644369, -0.46562647, -0.34735614],
       [ 0.26803284,  0.01767343,  0.3008666 , -0.91505483],
       [ 0.69225722, -0.19897566, -0.69307322, -0.02895072],
       [ 0.23047066, -0.83269577,  0.46078281,  0.20292912]])

In [116]:
D2 = np.hstack((np.diag(S2),np.zeros((3,1))))

In [118]:
U2.dot(D2).dot(V2)

array([[0.92092888, 0.40218799, 0.18123735, 0.19288555],
       [0.78815477, 0.70799252, 0.87968504, 0.01257624],
       [0.79319352, 0.81420399, 0.64577955, 0.9737995 ]])

In [119]:
A

array([[0.92092888, 0.40218799, 0.18123735, 0.19288555],
       [0.78815477, 0.70799252, 0.87968504, 0.01257624],
       [0.79319352, 0.81420399, 0.64577955, 0.9737995 ]])

In [120]:
U2.dot(U2.T)

array([[ 1.00000000e+00,  3.42316454e-16, -2.05308749e-17],
       [ 3.42316454e-16,  1.00000000e+00, -3.17574729e-16],
       [-2.05308749e-17, -3.17574729e-16,  1.00000000e+00]])

In [121]:
V2.dot(V2.T)

array([[ 1.00000000e+00,  0.00000000e+00,  1.80411242e-16,
         5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00, -2.84494650e-16,
         1.66533454e-16],
       [ 1.80411242e-16, -2.84494650e-16,  1.00000000e+00,
         2.77555756e-16],
       [ 5.55111512e-17,  1.66533454e-16,  2.77555756e-16,
         1.00000000e+00]])

In [122]:
U.dot(U.T)

array([[ 1.00000000e+00,  8.41240024e-16, -7.16508004e-16],
       [ 8.41240024e-16,  1.00000000e+00,  1.14204587e-16],
       [-7.16508004e-16,  1.14204587e-16,  1.00000000e+00]])

In [123]:
V.dot(V.T)

array([[ 1.00000000e+00, -3.33066907e-16,  1.11022302e-16,
         1.11022302e-16],
       [-3.33066907e-16,  1.00000000e+00,  3.33066907e-16,
        -2.22044605e-16],
       [ 1.11022302e-16,  3.33066907e-16,  1.00000000e+00,
        -6.66133815e-16],
       [ 1.11022302e-16, -2.22044605e-16, -6.66133815e-16,
         1.00000000e+00]])